title: ptmsk create the first blog
author: ptmsk
email: huy.tranacc13042@hcmut.edu.vn
description: > # this means to ignore newlines until "baseurl:"
  Create my first blog thanks to the github-learning-lab

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
